Add a new test, test_parameter_type_long, which demonstrates that passing parameters of type long when an int is expected, causes an exception.
ERROR: test_parameter_type_long (test.test_core.CoreTests)
...
ValueError: Bad value for parameter limit of type 'int' - 5